#' Add a Markdown file with function references
#'
#' @param include_internal Boolean indicating if you want to include the documentation of internal (i.e non-exported functions). Default is TRUE. See Details.
#'
#'
#' @details This function is automatically called with `init_docsify()` by default. However, if you didn't want to create it at the beginning but you changed your mind after having run `init_docsify()`, you can run it on its own.
#'
#' If you don't want to include internal functions (i.e functions that are not exported by the package), include "@@keywords internal" in the roxygen block of the function concerned, and use `include_internal = FALSE`.
#'
#' @return Creates a Markdown file called "func_reference.md" in the folder "docs", and edit "_sidebar.md" to add a "Reference" section.
#' @export
#'
#' @examples
#' \dontrun{
#'
#' library(docsifier)
#'
#' # Create a test folder and a test package for the example
#'
#' test_folder <- tempdir()
#' setwd(test_folder)
#' devtools::create("dummy")
#' setwd("dummy")
#'
#' # Generate the minimal documentation for docsify.js
#'
#' init_docsify(add_reference = FALSE)
#'
#' # Generate the "Reference" page in the documentation
#'
#' add_function_references()
#' }

add_function_references <- function(
  include_internal = FALSE,
  section_above = NULL,
  type = "section"
){

  function_infos <- build_function_reference(
    include_internal = include_internal
  )


  # I need to convert function arguments (and their description)
  # into a markdown list, so that each argument has its own bullet
  # point.

  list_in_markdown <- lapply(function_infos, function(x) {
    argument <- x$argument
    argument_description <- x$argument_description

    list_args <- list()
    if (!is.null(argument)) {
      for (i in seq_along(argument)) {
        list_args[[i]] <- paste0("* `", argument[i], "`: ",
                                 argument_description[i], "\n \n")
      }
    }

    return(list_args)
  })

  # Append this markdown list to list of infos for each function

  for (i in seq_along(function_infos)) {
    function_infos[[i]]$markdown_list <- list_in_markdown[[i]]
  }

  # create the markdown text for each function

  markdownize <- lapply(function_infos, function(x) {
    paste0(
      "`", x$name, "` : ", x$title,
      "\n <details>",
      "\n <summary> More </summary> \n \n **Usage:** ",
      "\n ``` \n", x$usage, "\n ``` \n ",
      if (!is.null(x$argument)) {
        paste0(
          "\n **Arguments:** ", "\n",
          paste(unlist(x$markdown_list), collapse = ""), "\n"
        )
      },
      if (!is.na(x$examples)) {
        paste0("\n **Examples:** \n ```", x$examples, "\n ```")
      },
      "\n </details> \n \n",
      "--- \n \n"
    )
  })


  if (!fs::file_exists("docs/func_reference.md")) {
    fs::file_copy(
      system.file("templates/func_reference-template.md",
                  package = "docsifier"),
      "docs/func_reference.md"
    )
  } else {

    fs::file_copy(
      system.file(
        "templates/func_reference-template.md",
        package = "docsifier"
      ),
      "docs/func_reference.md",
      overwrite = TRUE
    )

  }

  # append the markdown text we made into the file

  invisible(
    lapply(markdownize, function(x) {
      cat(x, file = "docs/func_reference.md", append = TRUE)
    })
  )

  add_to_sidebar(
    file = "docs/func_reference.md",
    name = "Reference",
    section_above = section_above,
    type = type
  )

}


#' Gather the important info in .Rd files
#' @keywords internal

build_function_reference <- function(include_internal = TRUE) {

  # Read content of files in "/man"
  # This creates a single character vector

  man_files <- as.character(
    fs::dir_ls("man", regexp = "\\.[Rr]d$", type = "file")
  )

  # exclude files that contain \keyword{internal} as the
  # package developer specified that these files only provide
  # non-exported functions

  if (include_internal == FALSE) {
    files_to_exclude <- lapply(man_files, function(x){
      y <- readChar(x, file.info(x)$size)
      if (grepl("\\keyword{internal}", y, fixed=TRUE))
        x
    })
    files_to_exclude <- unlist(files_to_exclude)
    man_files <- man_files[!(man_files %in% files_to_exclude)]
  }


  # Remove some annoying characters from files

  man_files_content <- lapply(man_files, function(x) {
    y <- readChar(x, file.info(x)$size)
    z <- gsub("% Generated by roxygen2: do not edit by hand% Please edit documentation in", " ", y)
    # remove \n before the first function
    z <- gsub("usage\\{\\n", "usage\\{", z)
    # replace \\code{.} by `.`
    z <- gsub("\\\\code\\{([^}]*)}","`\\1`", z)
    return(z)
  })


  # Gather important info from each file

   function_infos <- lapply(man_files_content, function(x) {
    l <- list(
      name = get_in_text("name", x),
      title = get_in_text("title", x),
      usage = get_in_text("usage", x),
      argument = get_in_text("argument", x),
      argument_description = get_in_text("argument_description", x),
      examples = get_in_text("examples", x)
    )
  })

  return(function_infos)

}


