#' Add a Markdown file with function references
#'
#' @param include_internal Boolean indicating if you want to include the documentation of internal (i.e non-exported functions). Default is TRUE. See Details.
#'
#'
#' @details This function is automatically called with `init_docsify()` by default. However, if you didn't want to create it at the beginning but you changed your mind after having run `init_docsify()`, you can run it on its own.
#'
#' If you don't want to include internal functions (i.e functions that are not exported by the package), include "@@keywords internal" in the roxygen block of the function concerned, and use `include_internal = FALSE`.
#'
#' @return Creates a Markdown file called "reference.md" in the folder "docs", and edit "_sidebar.md" to add a "Reference" section.
#' @export
#'
#' @examples
#' \dontrun{
#'
#' library(docsifier)
#'
#' # Create a test folder and a test package for the example
#'
#' test_folder <- tempdir()
#' setwd(test_folder)
#' devtools::create("dummy")
#' setwd("dummy")
#'
#' # Generate the minimal documentation for docsify.js
#'
#' init_docsify(add_reference = FALSE)
#'
#' # Generate the "Reference" page in the documentation
#'
#' add_reference()
#' }

add_reference <- function(
  include_internal = FALSE,
  section_above = NULL,
  type = "section"
){

  list_man <- list.files("man/", pattern = ".Rd")
  list_man_md <- unlist(lapply(list_man, function(x) {
    Rd2markdown(rdfile = x, include_internal = include_internal)
  }))

  if (!fs::file_exists("docs/reference.md")) {
    fs::file_copy(
      system.file("templates/reference-template.md",
                  package = "docsifier"),
      "docs/reference.md"
    )
  } else {

    fs::file_copy(
      system.file(
        "templates/reference-template.md",
        package = "docsifier"
      ),
      "docs/reference.md",
      overwrite = TRUE
    )

  }

  # append the markdown text we made into the file

  cat(list_man_md, file = "docs/reference.md", append = TRUE)

  add_to_sidebar(
    file = "docs/reference.md",
    name = "Reference",
    section_above = section_above,
    type = type
  )

  message_validate("'Reference' section has been added.")

}


#' Gather the important info in .Rd files
#' @keywords internal

build_function_reference <- function(include_internal = TRUE) {

  # Read content of files in "/man"
  # This creates a single character vector

  man_files <- as.character(
    fs::dir_ls("man", regexp = "\\.[Rr]d$", type = "file")
  )

  # exclude files that contain \keyword{internal} as the
  # package developer specified that these files only provide
  # non-exported functions

  if (include_internal == FALSE) {
    files_to_exclude <- lapply(man_files, function(x){
      y <- readChar(x, file.info(x)$size)
      if (grepl("\\keyword{internal}", y, fixed=TRUE))
        x
    })
    files_to_exclude <- unlist(files_to_exclude)
    man_files <- man_files[!(man_files %in% files_to_exclude)]
  }


  # Remove some annoying characters from files

  man_files_content <- lapply(man_files, function(x) {
    y <- readChar(x, file.info(x)$size)
    z <- gsub("% Generated by roxygen2: do not edit by hand% Please edit documentation in", " ", y)
    # remove \n before the first function
    z <- gsub("usage\\{\\n", "usage\\{", z)
    # replace \\code{.} by `.`
    z <- gsub("\\\\code\\{([^}]*)}","`\\1`", z)
    return(z)
  })


  # Gather important info from each file

   function_infos <- lapply(man_files_content, function(x) {
    l <- list(
      name = get_in_text("name", x),
      title = get_in_text("title", x),
      usage = get_in_text("usage", x),
      argument = get_in_text("argument", x),
      argument_description = get_in_text("argument_description", x),
      examples = get_in_text("examples", x)
    )
  })

  return(function_infos)

}


